### ISSUE TITLE
SvelteKit2 complains about missing export

### ISSUE THREAD

**Issue by gwax** [joshnuss/svelte-stripe#101]
### Describe the bug

When building / running against a SvelteKit v2 project, I receive the following warning:

```
11:42:47 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-stripe@1.1.3

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

### Reproduction

1. Create an entirely new SvelteKit v2 project
2. Add svelte-stripe
3. run

### Severity

annoyance

### Additional Information

https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by joshnuss** [comment]
Issue is resolved in version `1.1.7`.

The repo has been upgraded to SvelteKit2.

Let me know if anyone encounters any more issues.
