### ISSUE TITLE
Embeddable Checkouts: Prefilled Emails.

### ISSUE THREAD

**Issue by sveltarne** [joshnuss/svelte-stripe#102]
### Describe the problem

Most of the time, the user has already made an account by the time they go to checkout, so it would speed up things to...

### Describe the proposed solution

...have the email be able to be prefilled in the embedded checkout component. It should be a variable that you can give to the svelte component. `<EmbeddedCheckout prefilledEmail="hiohiohiohihoh@gmail.com" />`

### Importance

Nice to have

**Comment by joshnuss** [comment]
Hi @sveltarne,

This can be accomplished by setting `customer_email` when creating the checkout session.

For example:

```javascript
import Stripe from 'stripe'
import { SECRET_STRIPE_KEY, DOMAIN } from '$env/static/private'

const stripe = new Stripe(SECRET_STRIPE_KEY)
const return_url = new URL('/examples/embedded-checkout/thanks?session_id={CHECKOUT_SESSION_ID}', DOMAIN).toString()

export async function load() {
  const session = await stripe.checkout.sessions.create({
    customer_email: 'user@example.com',  // <----
    ui_mode: 'embedded',
    line_items: [
       // ...
    ],
    mode: 'payment',
    return_url
  })

  return {
    clientSecret: session.client_secret
  }
}
```
