### ISSUE TITLE
I cannot get the LinkAuthenticationElement example to work

### ISSUE THREAD

**Issue by rif** [joshnuss/svelte-stripe#105]
### Describe the bug

the LinkAuthenticationElement demo page works fine but when I am using even exactly the example code entering the email has no effect. Any hints?

### Reproduction

Set up the project and run the examples/payment-element locally

### Severity

serious, but I can work around it

**Comment by joshnuss** [comment]
Hi @rif,

Are you seeing any warnings or errors in the DevTools console?

Can you try it with the official Stripe example code using the same credentials:
https://github.com/stripe-samples/link

LMK

**Comment by rif** [comment]
This comment from the link you provided solved my problem:

`// Best practice is to enable Link through the dashboard and use automatic payment methods. For this demo, we explicitly pass payment_method_types: ['link', 'card'], to be extra clear which payment method types are enabled. automatic_payment_methods: { enabled: true },`

I had to go to stripe -> settings -> payment methods and enable the Link payment method.

Thank you for your help!
