### ISSUE TITLE
types are incompatible with latest @stripe/stripe-js@3.3.0

### ISSUE THREAD

**Issue by stanf0rd** [joshnuss/svelte-stripe#110]
### Describe the bug

Now svelte-stripe uses `@stripe/stripe-js@2.4.0` under the hood. But if I pass `stripe` object of type `Stripe` imported from `@stripe/stripe-js@3.3.0`, used in my project, I receive the following (poorly readable) ts error: 

```
Type 'import("/node_modules/@stripe/stripe-js/dist/stripe-js/stripe").Stripe' is not assignable to type 'import("/node_modules/svelte-stripe/node_modules/@stripe/stripe-js/types/stripe-js/stripe").Stripe'.
  The types of 'elements(...).create' are incompatible between these types.
    Type '{ (elementType: "address", options: import("/node_modules/@stripe/stripe-js/dist/stripe-js/elements/address").StripeAddressElementOptions): import("/node_modules/@stripe/stripe-js/dist/stripe-js/elements/address").StripeAddressElement; (elementType: "paym...' is not assignable to type '{ (elementType: "address", options: import("/node_modules/svelte-stripe/node_modules/@stripe/stripe-js/types/stripe-js/elements/address").StripeAddressElementOptions): import("/node_modules/svelte-stripe/node_modules/@stripe/stripe-js/types/stripe-js/elem...'.
      Types of parameters 'elementType' and 'elementType' are incompatible.
        Type '"cart"' is not assignable to type '"address"'.
```

```svelte
<script lang="ts">
  import { loadStripe, type Stripe } from '@stripe/stripe-js'
  import { Elements } from 'svelte-stripe'
  import { onMount } from 'svelte'

  let stripe: Stripe | null

  onMount(async () => {
    stripe = await loadStripe('abc')
  })
</script>

{#if stripe}
  <Elements {stripe}>
    <!--  Error here -->
  </Elements>
{/if}
```

It is difficult to workaround this issue (svelte does not allow `ts-ignore` inside markup). Also ignoring ts errors is not a best workaround :)

### Reproduction

I made a reproduction repo with this error. Make `npm install` and look into `src/+page.svelte` file OR run `npm run check`
https://github.com/stanf0rd/svelte-stripe-ts-error-repro

### Severity

annoyance

**Comment by joshnuss** [comment]
I don't really use TS, so I'll leave this open and hopefully someone will provide a solution/PR.

**Comment by kschniedergers** [comment]
I think you just need to update the @stripe/stripe-js package to the new version but idk what that would potentially break

**Comment by RealSocius** [comment]
Just stumbled upon this issue. I will look into it and possibly create a PR.

**Comment by joshnuss** [comment]
Thanks @RealSocius, PRs welcome

**Comment by hmnd** [comment]
@joshnuss I may be able to submit a PR for this today. Quick question before I look into it though: is there a particular reason for including `@stripe/stripe-js` as a direct dependency, instead of just a required peer dependency?

**Comment by joshnuss** [comment]
Probably should be a peer dependency, but there should be a minimum version set. 

Since some components won't exist in old versions of `@stripe/stripe-js`

**Comment by hmnd** [comment]
@joshnuss agreed. Since it could be considered a breaking change, it might be worthwhile releasing it as a new major version, too.

**Comment by joshnuss** [comment]
Do you think it's a breaking change?

The current version is 1.1.7, I would just put out a new minor release, ie 1.2.0

Note: this repo's release is automated using semantic-release, so the commit messages should contain `feat:` for a minor version increase

**Comment by hmnd** [comment]
It's not technically a breaking change in code/implementation, as stripe's v3 was just due to some esm output changes.

However, users of `svelte-stripe` would need to install `@stripe/stripe-js` separately upon updating if they don't have their package manager set to auto install peer deps. I guess npm should warn them of this, so a note in the changelog might suffice.

**Comment by joshnuss** [comment]
Good point.

I guess then it should remain a full dependency, that way it's easier to install.
Like, is there any advantage to being a peer dependency for this project?

**Comment by hmnd** [comment]
I would still favor peer dependencies, as it reduces the likelihood of two different versions of the same package being installed. Given how the end user has to create and pass in their own stripe-js client, they should explicitly include it in their own dependencies.

I think any packages that the user is likely to require in combination with a package you publish should be specified as peer deps. Whereas non peer deps should be reserved for utilities that you only use internally in your package. May not apply to stripe necessarily, but I've seen some nasty bugs from having packages that depend on conflicting minor versions.

**Comment by joshnuss** [comment]
Good points, thanks for the explanation.

So let's switch stripe-js to a peer dep, and the docs will need to updated and the changelog too.

Do you know what the error will look like if the peer dep isn't installed? Will `vite dev`/`vite build` fail? Cause I'd like to avoid people updating and then discovering a missing dep in production

**Comment by hmnd** [comment]
If the user doesn't have `@stripe/stripe-js` installed, vite dev and build will both fail with an error[^1]. But as I mentioned, if they used your docs to set it up, they would have actually had to install `@stripe/stripe-js` already, even though the docs don't explicitly mention needing to install it[^2].

[^1]: ![image](https://github.com/joshnuss/svelte-stripe/assets/12853597/58690f0f-dcb4-4d82-8267-a5537a2187ae)
[^2]: ![image](https://github.com/joshnuss/svelte-stripe/assets/12853597/f4353f67-51b9-4741-b6f1-ff911e6cf1ad)

**Comment by hmnd** [comment]
Oh and if the user has `auto-install-peers=false` (true by default) in their .npmrc, they'll get [this error](https://pnpm.io/errors#err_pnpm_peer_dep_issues). Otherwise, I believe the peer dep should auto install.

**Comment by joshnuss** [comment]
OK perfect!
