### ISSUE TITLE
Update @stripe/stripe-js to ^3.0.0|^4.0.0

### ISSUE THREAD

**Issue by jcarrillosrc** [joshnuss/svelte-stripe#120]
### Describe the problem

The current version of @stripe/stripe-js is 4.* and i would like to upgrade this dependency using this package. 

### Describe the proposed solution

Upgrade package.json to use version 4

### Importance

Would make my life easier

**Comment by frederichoule** [comment]
Any plan on doing that @joshnuss ?

Thanks!

**Comment by joshnuss** [comment]
Fixed in 99925e167e1fed5a9899b5adab9b2cf5244178a3

**Comment by frederichoule** [comment]
Thanks @joshnuss ! Do you plan to release soon or should we use the commit as the version in the meantime?

**Comment by joshnuss** [comment]
Yes! Just release [v1.2.1](https://www.npmjs.com/package/svelte-stripe/v/1.2.1)
