### ISSUE TITLE
Document how styling works

### ISSUE THREAD

**Issue by northkode** [joshnuss/svelte-stripe#17]
It seems there is no default styles.. 
How do we inject the styles or configs for svelte?

![image](https://user-images.githubusercontent.com/6988083/146622795-ecdbdd36-ce62-42be-8f59-7766a2376322.png)

**Comment by joshnuss** [comment]
Hi @northkode,

Which component are you using? `<Card/>`?

I think I need to add info about styling to the docs site.

**Comment by northkode** [comment]
Hey there, I'm using 
<CardNumber />
<CardExpiry />
<CardCvc />

Also i'm having issues with the Payment Element.. but i'm trying to work my way through the docs.

**Comment by joshnuss** [comment]
For styling those components, take a look at this example:
https://github.com/joshnuss/svelte-stripe-js/blob/main/src/routes/examples/credit-card/index.svelte

All those components accept a `classes` and `style` props. See options for [classes](https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-classes).

A general approach is to add a "base" class:, ie `<CardNumber classes={{base: 'input'}}/>`, and then define a CSS style for `.input`. And don't forget to use `:global(.input)` since these inputs are outside svelte's domain.

And let me know if you find any rough patches in the docs. They are quite new and I am looking for improve them.

Also what issue were you having with `<PaymentElement>`?

**Comment by northkode** [comment]
Ok Sounds good.. i think i see something missin with the payment element.. it accepts an option param where we can pass fields in to control what is shown.. it looks like you dont allow that to be send in via the mount function, that eventually calls elements.create('type', options) 

![image](https://user-images.githubusercontent.com/6988083/146624063-495871e1-9648-40d8-a987-581a93a5dc60.png)

**Comment by joshnuss** [comment]
I think in the case of PaymentElement those options are passed when calling `stripe.elements()`
https://github.com/joshnuss/svelte-stripe-js/blob/58b4d1c28f2c9307d2346150efeed7737b6e331a/src/lib/PaymentElement.svelte#L11

**Comment by northkode** [comment]
I updated your component locally.. to support the feature and now the options work 

for example 

```
let paymentOptions = {
	readOnly:true,
	fields: {
	    billingDetails: {
	      name: 'never',
	      email: 'never',
	    }
  	}
}
<PaymentElement options={paymentOptions}/>
```

And now my form is read only.. so if possible it would be good if you could make this upgrade official :D

**Comment by joshnuss** [comment]
Ah, I see what you mean now. The component should be taking more options.

I'll open a PR

**Comment by northkode** [comment]
Awesome Thanks! 
Appreciate the work on this. Definitely saved me some time.

**Comment by northkode** [comment]
I have a few more suggestions.. maybe ill try and submit a pr.. 
Things like 
changing the `let element` to a export
so we can bind on it and listen to events on the stripe element, like "change" events 
pass $$props into the component so i can style the wrapper div of the Payment Element etc.

**Comment by joshnuss** [comment]
Hi,

I deployed a new version `0.0.12` that adds an `options` prop to `<PaymentElement/>`.

For `<PaymentElement/>` and `confirmPayment()`, have a look at this example code:
https://github.com/joshnuss/svelte-stripe-js/tree/main/src/routes/examples/payment-element

**Comment by hex** [comment]
Is there an `options` prop to `<PaymentElement/>`? How can I achieve this with svelte-stripe?

```javascript
      // Pre-fill customer data using the defaultValues option. Passing in the email
      // is required for this integration. The other fields are optional.
      <PaymentElement
        options={{
          defaultValues: {
            billingDetails: {
              email: 'foo@bar.com',
              name: 'John Doe',
              phone: '888-888-8888',
            }
          }
        }}
```

**Comment by joshnuss** [comment]
@hex looks like those options are missing. I will add them.

Will let you know when it's in. Thanks for reporting.
