### ISSUE TITLE
svelte-stripe will not build on vite v2.8.6 / sveltekit 294

### ISSUE THREAD

**Issue by ZetiMente** [joshnuss/svelte-stripe#26]
Hi, 

I tried to run the following code:

<script  >
import { Container } from  'svelte-stripe';

let stripe = null; 

</script>

However, on pnpm build - svelte-kit build --verbose 
  
I receive the following error: 
  
  [vite:resolve] Failed to resolve entry for package "svelte-stripe". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "svelte-stripe". The package may have incorrect main/module/exports specified in its package.json.
> Failed to resolve entry for package "svelte-stripe". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "svelte-stripe". The package may have incorrect main/module/exports specified in its package.json.

I am running "svelte-stripe": "^0.0.13"

**Comment by joshnuss** [comment]
Hi @ZetiMente,

Thanks for reporting the issue.

I've investigated and there was a problem with how the npm package was published for `v0.0.13`.

Can you bump your project to `v0.0.16`, that should fix the issue. Can you try that and report back if it is solved?

**Comment by joshnuss** [comment]
@ZetiMente let me know if this still an issue or if I can close it. 🙏

**Comment by ZetiMente** [comment]
@joshnuss Hi, yes I was able to build. Thank for fixing it!

**Comment by joshnuss** [comment]
Awesome!

Feel free to open an issue if you run into anything else.
