### ISSUE TITLE
Seems legal policies are not shown?

### ISSUE THREAD

**Issue by mike-hogan** [joshnuss/svelte-stripe#42]
I configured legal policies for my account on stripe as per https://stripe.com/docs/payments/checkout/customization#configure-support-and-legal-policies , and I turned on "Display agreement to legal terms" in https://dashboard.stripe.com/settings/checkout .

I expected to see a checkbox forcing a customer to agree to terms before clicking pay, but that didn't happen.

Might be me as this is my first time using stripe, but might also be a missing feature of the svelte adapter?

**Comment by mike-hogan** [comment]
I am using PaymentElement like this:

```
            <PaymentElement
                    {stripe}
                    {clientSecret}
                    bind:elements
                    theme="flat"
                    labels="floating"
                    variables={{colorPrimary: '#7c4dff'}}
                    rules={{'.Input': { border: 'solid 1px #0002' }}}
            />

```

**Comment by joshnuss** [comment]
Hey @mike-hogan,

`<PaymentElement>` and the other components provided by this repo use Stripe Elements. It's different than using Stripe Checkout.

With Stripe Checkout the entire payment flow is handled outside your site. With Stripe Elements the payment flow is handled on your site and you would have to create your own UI to display terms and conditions.

If you'd like to use Stripe Checkout, this is how you'd do it:

1. Add button, when the user clicks call the backend to create a Stripe Checkout Session
2. Add an endpoint to create the checkout session, see: https://stripe.com/docs/api/checkout/sessions/create
3. Redirect the user to the `url` that Stripe returns in Step 2
4. Add an endpoint to handle the `checkout.session.completed` webhook, Stripe will send that when the checkout was successful, see: https://stripe.com/docs/payments/checkout/fulfill-orders

I believe this should resolve this issue. Feel free to re-open if you have any more questions.
