### ISSUE TITLE
Elements custom fonts

### ISSUE THREAD

**Issue by daniel-panhead** [joshnuss/svelte-stripe#54]
I am working with the `CardNumber`, `CardCvc`, and `CardExpiry` elements, and unfortunately I wasn't able to get custom fonts working with the styling method shown in the examples.

However, in the stripe.js docs, when creating a new elements object there is the option to specify a `fonts` property which allows custom fonts to be used. However, currently the `Elements` component does not support this property. I believe adding this functionality shouldn't be too difficult since the `@stripe/stripe-js` package provides support for this already.

`Elements.svelte` just needs to accept a font variable:
```

/** @type {StripeElementsOptions["fonts"]} */
export let fonts = []
...
export let elements = isServer ? null : stripe.elements({ appearance: { theme, variables, rules, labels }, clientSecret, fonts, loader })
```

As well as the appropriate type being added to `Elements.svelte.d.ts`:
```
fonts?: import('@stripe/stripe-js').StripeElementsOptions["fonts"];
```

I tested these changes out on my local machine and I was able to get a custom Google font to work.

**Comment by steveninety** [comment]
Hey what a coincidence, I did the exact same thing yesterday using a local font. That means we're about equally autistic when it comes to styling.
 
For anyone else doing this, you might get some font sanitization error in Firefox.
To solve that, add `format('yourformattype')` at the end of your src value, for example:

```
[{            
    family: "'customFont'",
    src: "'url(https://mywebsite.com/fonts/custom-font.woff) format('woff')'",
    weight: '400'
  }]
```

I also added the update method that comes with the StripeElements (Elements) component:

```
export function update(options) {
  elements.update(options)
}
```

You can pass in the appearance object. I use it to add different styles when toggling dark mode.

**Comment by daniel-panhead** [comment]
I am actually using a remote font for my project. For the appearance object, I read in the docs that it only supports the Payment Elements object. However, I am using the individual CardNumber, etc. elements which I don't think will support this. 

I have created a PR (#55) with the change for the fonts, which is really only a few lines in the `Elements.svelte` file. Please let me know if there is anything wrong with it. Thanks!
