### ISSUE TITLE
Changing locale of Elements

### ISSUE THREAD

**Issue by ErikSandquist** [joshnuss/svelte-stripe#59]
### Describe the problem

I want my Stripe elements to be in a specific language all the time. It is not supported to change the language known in stripe docs as locale in the current state. 

### Describe the proposed solution

I would like an option to send a locale option when calling the Elements in svelte. This can be done when calling it in the source code with all the other options such as appearance and style ([see stripe docs](https://stripe.com/docs/js/elements_object/create#stripe_elements-options-locale))

### Importance

Nice to have

**Comment by joshnuss** [comment]
Hi @ErikSandquist,

Thanks for reporting!

I see you forked the repo and added a fix, feel free to open a PR

**Comment by joshnuss** [comment]
Issue is now resolved in #62
