### ISSUE TITLE
Error when the payment modal is opened the second time

### ISSUE THREAD

**Issue by lockieluke** [joshnuss/svelte-stripe#60]
### Describe the bug

`<Elements />` is put into a modal that is opened on demand.  However, if you close the modal and open it again, it will show the following error:

```
Uncaught (in promise) IntegrationError: Can only create one Element of type payment.
```

I believe there's something wrong with the `bind:elements` in `<Elements />`

### Reproduction

```svelte
<Modal bind:open={payModal} permanent={processing}>
    <div class="bg-white rounded-lg p-5">
        <div class="flex items-center my-5">
            <img src={BIcon} width="50" height="50" />
            <p class="text-2xl font-bold text-black mx-2">B</p>
        </div>
        {#if stripe && clientSecret}
            <div class="my-5">
                <Label for='email-input' class='block mb-2'>Email Address</Label>
                <Input id="email-input" type="email" size="lg" placeholder="name@bacherry.com">
                    <svg slot="left" aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
                </Input>
            </div>
            <Elements {stripe} {clientSecret} bind:elements>
                <form on:submit|preventDefault={onSubmit} id="payment-form">
                    <PaymentElement />
                </form>
                <Button type="submit" form="payment-form" disabled={processing} class="my-5">
                    {#if processing}
                        <Spinner class="mr-3" size="4" color="white" />
                    {/if}
                    Pay
                </Button>
            </Elements>
        {/if}
        <p class="text-gray-700 italic font-light">Payment powered by Stripe</p>
    </div>
</Modal>
```

You can use any kind of modal, in this case I'm using Flowbite's `<Modal />`, you just have to close and reopen the modal and the error will appear.

### Severity

annoyance

### Additional Information

I know `<Elements />` was probably not meant to be put in a popup/modal but it would be nice if this can be fixed

**Comment by joshnuss** [comment]
Hi @lockieluke,

Thanks for reporting!

I verified that is indeed a bug, and I've opened a fix in #61.

**Comment by joshnuss** [comment]
@lockieluke wanna give the main branch a try and report back if it fixes your issue?

**Comment by lockieluke** [comment]
> @lockieluke wanna give the main branch a try and report back if it fixes your issue?

Will do

**Comment by lockieluke** [comment]
> @lockieluke wanna give the main branch a try and report back if it fixes your issue?

I'm using `Yarn 3`(I know niche), it doesn't let me install the package from git

**Comment by joshnuss** [comment]
I believe it should work (though I've not tried myself)

Maybe something like this:
https://stackoverflow.com/a/67779901/306520

**Comment by lockieluke** [comment]
Just tried it said `workflow not supported`

**Comment by joshnuss** [comment]
No worries! 

I tested it locally and the fix does work. So I just publushed a new version `0.0.22` to npm.

Try bumping the package to that version in your `package.json`.

**Comment by lockieluke** [comment]
Thanks!

**Comment by lockieluke** [comment]
Just tested it, it works!
