### ISSUE TITLE
Does not work in Astro

### ISSUE THREAD

**Issue by silveltman** [joshnuss/svelte-stripe#69]
### Describe the bug

Get an error in Astro whhen using a component containing <Elements> or any other component from this repo.

Tried both client:load and client:only. Would seem to me that client:only should work, because it is just svelte, but maybe my knowlegde in lacking here.

onMount function is not fired at all.

error:
`[HMR][Svelte] Unrecoverable HMR error in <SvelteStripe>: next update will trigger a full reload`

### Reproduction

1. Create an astro project
2. create an astro page
3. create a svelte component with the following code:
```
<script>
  import { loadStripe } from '@stripe/stripe-js'
  import { Elements, PaymentElement } from 'svelte-stripe'
  import { onMount } from 'svelte'
  import Stripe from 'stripe'

  async function createPaymentIntent() {
    return await stripeSecret.paymentIntents.create({
      amount: 2000,
      currency: 'eur',
      automatic_payment_methods: {
        enabled: true,
      },
    })
  }

  async function confirmPayment() {
    return await stripeSecret.confirmPayment({
      elements,
    })
  }

  let stripePublic = null
  let stripeSecret = null
  let clientSecret = null
  let elements

  onMount(async () => {
    console.log('onMount')
    stripePublic = await loadStripe(
      'yourpublickey'
    )
    stripeSecret = new Stripe(
      'yourtestkey'
    )
    clientSecret = await createPaymentIntent()

    console.log('stripePublic', stripePublic)
    console.log('stripeSecret', stripeSecret)
    console.log('clientSecret', clientSecret)
  })
</script>

<h1>Hello svelte stripe</h1>
<form on:submit|preventDefault={confirmPayment}>
  <Elements
    stripe={stripePublic}
    {clientSecret}
    bind:elements
  >
    <PaymentElement />
  </Elements>

  <button>Pay</button>
</form>
```
4. import it with <YourSvelteComponent client:load/> or <YourSvelteComponent client:only/>

### Severity

blocking all usage

### Additional Information

Astro version 3.0.7

**Comment by silveltman** [comment]
Unfortunately I was just testing some stuff out and refactored the code to using the native javascript stripe elements. I will leave this open for once I get back to working with stripe on my astro project

**Comment by joshnuss** [comment]
Looking into the issue further, it appears Astro is geared towards server-side rendering. But svelte-stripe is based on @stripe/stripe-js, which is a client rendered.

So adding svelte-stripe as a dependency to an Astro project directly wouldn't work.

Instead, you can build a separate `.js` that you can load in your Astro page on the client:

- Create a new vite project `pnpm create vite payment-page`
- Choose the `svelte` template (without SvelteKit)
- Add a component for your payment section, ie `MyPaymentCard.svelte`
- Place some components from `svelte-stripe` in your payment component
- Configure `src/main.js` to specify where to mount the `MyPaymentCard` component
- Build the project `pnpm build` and copy the build to your Astro project's `/public` folder
- Import the script in your Astro payment page `<script is:inline src="/payment-page.js"/>`

Hope that helps, let me know if you have any further questions!
