### ISSUE TITLE
Address Component Type requires multiple props than just Mode (based off of example)

### ISSUE THREAD

**Issue by markkhoo** [joshnuss/svelte-stripe#70]
### Describe the bug

Based on the example of the `<Address>` component used in the [example here](https://github.dev/joshnuss/svelte-stripe/tree/main/src/routes/examples/payment-element), the component only uses the prop of `mode`.  Based on the type definition, the `<Address>` component requires: `allowCountries`, `blockPoBox`, `defaultValues`, `fields`, `validation`, `contacts`, and `display`. 

### Reproduction

Use the address component from the [example](https://github.dev/joshnuss/svelte-stripe/tree/main/src/routes/examples/payment-element) and see the type errors.

### Severity

annoyance

**Comment by joshnuss** [comment]
Thanks for reporting!

The issue is now resolved.
