### ISSUE TITLE
How do I listen to element events?

### ISSUE THREAD

**Issue by shkvoretz** [joshnuss/svelte-stripe#74]
### Describe the bug

How do I listen to element events?

There appears to be no event handlers on element component

[https://stripe.com/docs/js/element/events/on_loaderror](https://stripe.com/docs/js/element/events/on_loaderror)

I get 'Unhandled payment Element loaderror' error

### Reproduction

How do I listen to element events?

There appears to be no event handlers on element component

[https://stripe.com/docs/js/element/events/on_loaderror](https://stripe.com/docs/js/element/events/on_loaderror)

I get 'Unhandled payment Element loaderror' error

### Severity

serious, but I can work around it

**Comment by joshnuss** [comment]
Hi @shkvoretz!

The issue is now resolved.

Here is an example of using the events:

```html
<PaymentElement
  on:loaderstart={e => console.log(e.detail)}
  on:loaderror={e => console.log(e.detail)}
  />
```

**Comment by shkvoretz** [comment]
@joshnuss Legend! Thank you! 🙏
