### ISSUE TITLE
Issue with PaymentElement default value for name

### ISSUE THREAD

**Issue by chewbakartik** [joshnuss/svelte-stripe#96]
### Describe the bug

When attempting to load default value for the name field of the PaymentElement. The value passed into the options is not pre-filling the input.
I am attempting to pass values to both the Email and the Name fields, and only the email's default value is showing.

### Reproduction

Taking the PaymentElement example, you can attempt to pass the default values like below and see that the email works, but the name doesn't.
```
<Elements
...
<PaymentElement 
  options={{
    defaultValues: {
      billingDetails: {
        name: 'Bob',
        email: 'bob@bob.com'
      }
    }
  }}
  />
</Elements>
```

### Severity

annoyance

### Additional Information

I'm not sure what's going on for it to partially work for one value and not the other. I've triple checked the stripe docs to make sure the object I'm passing in is in the right format and targeting the correct property names. I've also attempted to downgrade the stripe libs to as low as 13.11 to see if that's able to resolve it with no success.
Thanks for a great library, let me know what I can do to help test and sort this out.

**Comment by joshnuss** [comment]
Hi @chewbakartik,

After investigating, I don't think it's an issue with this library. Because the `defaultValues` are passed right thru.

Might have to open an issue with Stripe or ask on the Stripe Discord channel (very quick response time).

**Comment by chewbakartik** [comment]
Hi @joshnuss,

Thanks for the quick response. It didn't seem likely that it was a bug with the library as we can see that a value is being able to be set. I'll check on the Stripe discord and see if there's anyone else experiencing a similar problem and add info back on this issue. It can hopefully help out any others that are experiencing a similar problem.

**Comment by chewbakartik** [comment]
Hi @joshnuss so I managed to get it working by changing some of the setup around. It may be a good idea to update the docs or expand the example in order to help others who may come across the same struggles.
So in my particular case, I realize my initial ask didn't include all the components I was showing.
```
<Elements
  {stripe}
  {clientSecret}
  bind:elements>
  <form on:submit|preventDefault={submit}>
    //Needed to show email, but doesn't take default value
    <LinkAuthenticationElement />
    // Email needed to be passed as default value here in order to be displayed in LinkAuthentication
    <PaymentElement options={{ defaultValues: { billingDetails: { email: emailValue} } }} />
    <Address mode="billing" defaultValues={{ name: nameValue }} />
    <button>Submit</button>
    </form
```

**Comment by chewbakartik** [comment]
Sound good, the dev assisting me in the Stripe discord mentioned that part of the guides is a guideline, as there are some forms of the payment element that include name and email, it depends on the context.

I do think it might make sense to have an example in the docs of your default PaymentElement that includes default values as I think that's useful. At  the very least someone can be pointed to this issue if they have questions.

**Comment by joshnuss** [comment]
I'd prefer to wait to see if others are having this issue before I commit to increasing the size of the docs.

Thanks for the offer though! much appreciated
